from datetime import datetime

books = [
    {
        "title": "The Great Gatsby",
        "author": "F. Scott Fitzgerald",
        "content": "The Great Gatsby is a novel about a wealthy man named Jay Gatsby who throws extravagant parties in hopes of winning back his former love, Daisy Buchanan. Set in the 1920s, the novel explores themes of love, wealth, and the decline of the American Dream.",
        "pages": 180,
        "created_at": datetime.now().strftime("%Y-%m-%d %H:%M"),
        "last_updated": datetime.now().strftime("%Y-%m-%d %H:%M"),
    },
    {
        "title": "To Kill a Mockingbird",
        "author": "Harper Lee",
        "content": "To Kill a Mockingbird is a novel about a young girl named Scout Finch growing up in the deep South during the Great Depression. The novel explores themes of racism and prejudice through the eyes of Scout and her family, particularly her father, Atticus Finch, who is appointed to defend a black man falsely accused of rape.",
        "pages": 281,
        "created_at": datetime.now().strftime("%Y-%m-%d %H:%M"),
        "last_updated": datetime.now().strftime("%Y-%m-%d %H:%M"),
    },
    {
        "title": "The Catcher in the Rye",
        "author": "J.D. Salinger",
        "content": "The Catcher in the Rye is a novel about a teenage boy named Holden Caulfield, who is kicked out of his prep school and spends a few days wandering around New York City. The novel explores themes of alienation, loss of innocence, and the struggles of growing up.",
        "pages": 214,
        "created_at": datetime.now().strftime("%Y-%m-%d %H:%M"),
        "last_updated": datetime.now().strftime("%Y-%m-%d %H:%M"),
    },
    {
        "title": "1984",
        "author": "George Orwell",
        "content": "1984 is a novel set in a dystopian society where the government exerts total control over its citizens. The novel follows the story of Winston Smith, a low-ranking member of the ruling Party, as he begins to question the regime and his own sanity. The novel explores themes of totalitarianism, censorship, and the dangers of a surveillance state.",
        "pages": 328,
        "created_at": datetime.now().strftime("%Y-%m-%d %H:%M"),
        "last_updated": datetime.now().strftime("%Y-%m-%d %H:%M"),
    },
    {
        "title": "The Lord of the Rings",
        "author": "J.R.R. Tolkien",
        "content": "The Lord of the Rings is an epic fantasy novel about hobbit Frodo Baggins, who is entrusted with the task of destroying the One Ring, a powerful and evil ring created by the Dark Lord Sauron. The novel explores themes of friendship, courage, and the struggle between good and evil.",
        "pages": 1216,
        "created_at": datetime.now().strftime("%Y-%m-%d %H:%M"),
        "last_updated": datetime.now().strftime("%Y-%m-%d %H:%M"),
    },
    {
        "title": "The Hitchhiker's Guide to the Galaxy",
        "author": "Douglas Adams",
        "content": "The Hitchhiker's Guide to the Galaxy is a comedic science fiction series following the misadventures of an unwitting human and his alien friend as they travel through space. The novel explores themes of absurdity, satire, and the ultimate futility of human endeavors.",
        "pages": 324,
        "created_at": datetime.now().strftime("%Y-%m-%d %H:%M"),
        "last_updated": datetime.now().strftime("%Y-%m-%d %H:%M"),
    },
    {
        "title": "The Hobbit",
        "author": "J.R.R. Tolkien",
        "content": "The Hobbit is a novel about hobbit Bilbo Baggins, who is hired by a group of dwarves to help them reclaim their homeland from a dragon named Smaug. The novel explores themes of adventure, friendship, and the power of imagination.",
        "pages": 320,
        "created_at": datetime.now().strftime("%Y-%m-%d %H:%M"),
        "last_updated": datetime.now().strftime("%Y-%m-%d %H:%M"),
    },
    {
        "title": "Pride and Prejudice",
        "author": "Jane Austen",
        "content": "Pride and Prejudice is a novel about the lives and loves of the five Bennett sisters in Georgian England. The novel explores themes of societal pressure, marriage, and the subtle power struggles between men and women of the time.",
        "pages": 432,
        "created_at": datetime.now().strftime("%Y-%m-%d %H:%M"),
        "last_updated": datetime.now().strftime("%Y-%m-%d %H:%M"),
    },
    {
        "title": "The Diary of a Young Girl",
        "author": "Anne Frank",
        "content": "The Diary of a Young Girl is a non-fiction book that tells the story of Anne Frank, a Jewish girl who went into hiding with her family during World War II. The book is a collection of the diary entries she wrote while in hiding and gives a glimpse into the daily lives of Jewish people during the Holocaust.",
        "pages": 224,
        "created_at": datetime.now().strftime("%Y-%m-%d %H:%M"),
        "last_updated": datetime.now().strftime("%Y-%m-%d %H:%M"),
    },
    {
        "title": "Harry Potter and the Philosopher's Stone",
        "author": "J.K. Rowling",
        "content": "Harry Potter and the Philosopher's Stone is the first book in the Harry Potter series, it tells the story of an orphan boy named Harry Potter who discovers that he is a wizard and enrolls in Hogwarts School of Witchcraft and Wizardry. The book explores themes of friendship, bravery, and the struggle between good and evil.",
        "pages": 320,
        "created_at": datetime.now().strftime("%Y-%m-%d %H:%M"),
        "last_updated": datetime.now().strftime("%Y-%m-%d %H:%M"),
    },
]
